# .github/workflows/block-no-merge-label.yml
name: Block PRs with "no-merge" label
 
on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened, reopened]
 
jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for "no-merge" label
        uses: actions/github-script@v7
        with:
          script: |
            const labels = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
 
            const hasNoMerge = labels.data.some(label => label.name === "no-merge");
 
            if (hasNoMerge) {
              core.setFailed('This pull request has a "no-merge" label.');
            }
